### ISSUE TITLE
some notes

### ISSUE THREAD

**Issue by YesserFA** [Raxelgrande/awesome-touhou#7]
Hi, I read what you did here, it's very nice but I need some additions
Like there is an Arabic discord server for Touhou
Its name is ARABSOKYO | ArabSokyo 🇸🇦
And this is the link https://discord.gg/5nxSyGdmBA
And there are also servers for Touhou 15.5
This is the link https://discord.gg/kfJTRBq

**Comment by Raxelgrande** [comment]
Thanks for contributing, both suggestions are great and i added them under Commit [cb93a7d](https://github.com/Raxelgrande/awesome-touhou/commit/cb93a7d605cf305160def83548134f035b341b41)
